### ISSUE TITLE
Antergos-alerts error

### ISSUE THREAD

**Issue by lots0logs** [Antergos/antergos-alerts#2]
@Swipe650 commented on [Mon Jun 26 2017](https://github.com/Antergos/antergos-packages/issues/215)

```
[2017-06-26 07:14] [ALPM] running 'antergos-alerts.hook'...
[2017-06-26 07:14] [ALPM-SCRIPTLET] Traceback (most recent call last):
[2017-06-26 07:14] [ALPM-SCRIPTLET]   File "/usr/bin/antergos-alerts", line 144, in <module>
[2017-06-26 07:14] [ALPM-SCRIPTLET]     do_alerts()
[2017-06-26 07:14] [ALPM-SCRIPTLET]   File "/usr/bin/antergos-alerts", line 117, in do_alerts
[2017-06-26 07:14] [ALPM-SCRIPTLET]     subject, part1, part2, part3 = get_localized_alert_message()
[2017-06-26 07:14] [ALPM-SCRIPTLET]   File "/usr/bin/antergos-alerts", line 76, in get_localized_alert_message
[2017-06-26 07:14] [ALPM-SCRIPTLET]     subject = _('ATTENTION: Antergos System Message')
[2017-06-26 07:14] [ALPM-SCRIPTLET] NameError: name '_' is not defined
```

**Comment by karasu** [comment]
I also get this when building an ISO. I think it's because gettext is not yet installed or imported. I'll have a look at antergos-alerts asap ;)
